#!/usr/bin/env python

#   Copyright 2013 Zynga inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
"""
Online update control for ep-engine.

"""
import time
import sys
import clitool
import mc_bin_client

def auth(mc, username, password):
    if username:
        mc.sasl_auth_plain(username, password)

def revert(mc, username=None, password=""):
    try:
        auth(mc, username, password)
        mc.revert_onlineupdate()
    except mc_bin_client.MemcachedError as ne:
        sys.exit("ERROR: " + str(ne))
    finally:
        if mc:
           mc.close()

def start(mc, username=None, password=""):
    try:
        auth(mc, username, password)
        mc.start_onlineupdate()
    except mc_bin_client.MemcachedError as ne:
        sys.exit("ERROR: " + str(ne))
    finally:
        if mc:
           mc.close()

def complete(mc, username=None, password=""):
    try:
        auth(mc, username, password)
        mc.complete_onlineupdate()
    except mc_bin_client.MemcachedError as ne:
        sys.exit("ERROR: " + str(ne))
    finally:
        if mc:
           mc.close()

if __name__ == '__main__':

    c = clitool.CliTool("""
All commands allow an optional username and password as the last
two parameters.

Online update:
    start          - start online update and stop persistence
    complete       - stop online update and continue persistence
    revert         - stop online update and revert any mutations during online update
""")

    c.addCommand('start', start, 'start')
    c.addCommand('complete', complete, 'complete')
    c.addCommand('revert', revert, "revert")

    c.execute()
