#!/usr/bin/env python

#   Copyright 2013 Zynga inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import clitool

def listvb(mc, username=None, password=""):
    if username:
        mc.sasl_auth_plain(username, password)
    vbs = mc.stats('vbucket')
    for (vb, state) in sorted(list(vbs.items())):
        print "vbucket", vb[3:], state

def setvb(mc, vbid, vbstate, username=None, password=""):
    if username:
        mc.sasl_auth_plain(username, password)
    mc.set_vbucket_state(int(vbid), vbstate)

def rmvb(mc, vbid, username=None, password=""):
    if username:
        mc.sasl_auth_plain(username, password)
    mc.delete_vbucket(int(vbid))

if __name__ == '__main__':

    c = clitool.CliTool()

    c.addCommand('list', listvb, 'list [username password]')
    c.addCommand('set', setvb, 'set vbid vbstate [username password]')
    c.addCommand('rm', rmvb, 'rm vbid [username password]')

    c.execute()
